### ISSUE TITLE
Microsoft.Extensions.Logging.LoggerExtensions.LogError does not log provided exception.

### ISSUE THREAD

**Issue by bondarchook** [dotnet/dotnet-api-docs#10318]
### Description

When using Microsoft.Extensions.Logging.LoggerExtensions methods that allow exception to be passed for logging - exception get completely ignored and not logged at all.
 
It all comes down to private MessageFormatter method that completely ignores provided exception. 

https://github.com/dotnet/runtime/blob/07d8b82d54b6b8db16f5fbb531efcb1e276dc264/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/LoggerExtensions.cs#L417

According to this commit that I found in old repository 
https://github.com/aspnet/Logging/commit/4528bdbc2816a8b5f933d9c6cf2da806ce4a72ea
Method MessageFormatter use to have correct implementation and then was changed without any good explanation.
https://github.com/aspnet/Logging/commit/4528bdbc2816a8b5f933d9c6cf2da806ce4a72ea#:~:text=private%20static%20string%20MessageFormatter(object%20state%2C%20Exception%20error)

Commit that broke this is from 2016. So how this passed through testing for 6 years is a good question.

Affected methods:
LogTarce
LogDebug
LogInformation
LogWarning
LogError
LogCritical

### Reproduction Steps

Use Microsoft.Extensions.Logging.LoggerExtensions.LogError method to log exception 

```cs
                ILogger logger; // Instance of Microsoft.Extensions.Logging.ILogger 

                try
                {
                    throw new Exception("Test exception. This should be logged");
                }
                catch (Exception e)
                {
                    logger.LogError(e, "Test message that suppose to be logged together with exception");
                }

```

### Expected behavior

Provided exception details should be logged together with log message.

### Actual behavior

Provided exception completely ignored and only log message is logged.  

### Regression?

Yes since 2016

According to this commit that I found in old repository 
https://github.com/aspnet/Logging/commit/4528bdbc2816a8b5f933d9c6cf2da806ce4a72ea
Method MessageFormatter use to have correct implementation and then was changed without any good explanation.
https://github.com/aspnet/Logging/commit/4528bdbc2816a8b5f933d9c6cf2da806ce4a72ea#:~:text=private%20static%20string%20MessageFormatter(object%20state%2C%20Exception%20error)

### Known Workarounds

No

**Comment by tarekgh** [comment]
I have transferred the issue to the doc repo as I see there is an opportunity to improve the docs. @enioluwas are you interested in submitting PR for fixing the docs?

**Comment by davidfowl** [comment]
Yes we should improve the documentation and the doc comment. This was a design error made when the API was originally designed

**Comment by enioluwas** [comment]
> I have transferred the issue to the doc repo as I see there is an opportunity to improve the docs. @enioluwas are you interested in submitting PR for fixing the docs?

Sure!

**Comment by bh3605** [comment]
Does this mean the docs here are inaccurate? https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-add-modify?tabs=aspnetcore#add-custom-exceptions

I've been going in circles trying to call this extension method and it feels like no one is logging the exception when this extension is used.

**Comment by tarekgh** [comment]
@bh3605 please provide a complete sample reproducing the issue you are facing as it is not clear to me what exactly you are doing.

**Comment by bh3605** [comment]
@tarekgh I found the the OTEL_DIAGNOSTICS.json file to be incredibly helpful. I'm thinking this is why I'm not seeing the exception get logged.
`StatusCode: 206. Error from Ingestion: 109: Field 'method' on type 'StackFrame' is required but missing or empty. Expected: string. Action: Telemetry is dropped. Origin: AzureMonitorLogExporter. AAD Enabled: False. Instrumentation Key: xxx. Configured Endpoint: https://aaa.com/. Actual Endpoint: aaa.com`

I think the reason this problem is happening is because the error is coming from a class being invoked inside a delegate.

I'm using IMediatr and it's throwing the exception when it's resolving this service provider when it's resolving all of the IRequestHandler dependencies.
``` csharp
services.AddTransient(provider =>
{
	var factory = provider.GetRequiredService<ClarityBindingFactory>();

	var binding = factory.CreateBinding();
	var address = factory.CreateEndpointAddress();
	var cert = factory.LoadClientCertificate(); //<--- error here

	var client = new ClarityWebServiceSEIClient(binding, address);
	client.ClientCredentials.ClientCertificate.Certificate = cert;

	return client;
});
```


Here's my setup
``` csharp
public class Startup
{
	private IConfigurationManager Configuration;

	public Startup(IConfigurationManager configuration)
	{
		Configuration = configuration;
	}

	public void Configure(WebApplicationBuilder builder)
	{
		builder.Logging.ClearProviders();
	}

	public void ConfigureServices(IServiceCollection services)
	{
		services.AddOpenTelemetry().UseAzureMonitor();

		services.AddProblemDetails();
		services.AddExceptionHandler<ExceptionToProblemDetailsHandler>();
	}

	public void ConfigureMiddleware(WebApplication app, Action<SwaggerOptions>? swaggerSetupAction = null)
	{
		app.UseExceptionHandler();
		app.UseStatusCodePages();
		app.UseSwagger(swaggerSetupAction);
		app.UseSwaggerUI();

		app.UseAuthentication();
		app.UseAuthorization();
		app.UseHttpsRedirection();

		app.MapControllers().RequireAuthorization();
	}
}
```

Here's where I'm writing the logs
``` csharp
internal sealed class ExceptionToProblemDetailsHandler : IExceptionHandler
{
	private readonly IProblemDetailsService _problemDetailsService;
	private readonly ILogger<ExceptionToProblemDetailsHandler> logger;

	public ExceptionToProblemDetailsHandler(IProblemDetailsService problemDetailsService, ILogger<ExceptionToProblemDetailsHandler> logger)
	{
		_problemDetailsService = problemDetailsService;
		this.logger = logger;
	}

	public async ValueTask<bool> TryHandleAsync(HttpContext httpContext, Exception exception, CancellationToken cancellationToken)
	{
		httpContext.Response.StatusCode = exception switch
		{
			NotFoundException => StatusCodes.Status404NotFound,
			ValidationException => StatusCodes.Status400BadRequest,
			BadRequestException => StatusCodes.Status400BadRequest,
			UnsupportedFormatException => StatusCodes.Status415UnsupportedMediaType,
			_ => StatusCodes.Status500InternalServerError
		};
		// being careful not to leak specific exception details
		ProblemDetails details = exception switch
		{
			NotFoundException => new()
			{
				Title = "Not Found",
				Detail = "Requested resource was not found",
				Status = httpContext.Response.StatusCode,
				Instance = httpContext.Request.Path
			},
			ValidationException e => new ValidationProblemDetails()
			{
				Title = "Validation errors",
				Detail = "One or more validation errors were encountered",
				Status = httpContext.Response.StatusCode,
				Instance = httpContext.Request.Path,
				Errors = e.Errors.GroupBy(error => error.PropertyName)
								  .ToDictionary(x => x.Key,
												x => x.Select(y => y.ErrorMessage)
													  .Distinct()
													  .ToArray())
			},
			_ => new()
			{
				Title = "Internal server error",
				Detail = "Request failed unexpectedly",
				Status = StatusCodes.Status500InternalServerError,
				Instance = httpContext.Request.Path
			}
		};

		var problemDetailsContext = new ProblemDetailsContext()
		{
			HttpContext = httpContext,
			ProblemDetails = details
		};
		logger.LogTrace("Trace 1");
		logger.LogWarning("Warning 1");
		logger.LogError("Error 1");
		logger.LogCritical("Critical 1");
		logger.LogError(exception, "Log the ex");
		logger.LogError(exception, "Exception caught and converted to ProblemDetails {@ProblemDetails}", details);

		_ = await _problemDetailsService.TryWriteAsync(problemDetailsContext);

		return true;
	}
}
```

I'm getting double telemetry and the structured logs aren't showing for the aforementioned reason above.

<img width="621" height="176" alt="Image" src="https://github.com/user-attachments/assets/1acb2596-e340-4166-afa9-50f7f12142a0" />

<img width="301" height="184" alt="Image" src="https://github.com/user-attachments/assets/1f1d7993-5210-4dbb-9e2f-5be8d6cb7bc9" />

<img width="228" height="134" alt="Image" src="https://github.com/user-attachments/assets/492a0d87-43a0-4769-aa3f-fa55b1e9c2da" />

**Comment by ybondarchuk-rws** [comment]
OMG this is still not fixed?
It was undetected by QA for 6 years
Then I reported it, and after 3.5 years they still can not fix it? And instead they want to document it?
Microsoft, it is 5 minute fix, and it is still unfixed after 9.5 years - fix it already, would you.

**Comment by tarekgh** [comment]
@bh3605 Thanks for the details. Based on your setup, it looks like the issue isn’t actually with `Microsoft.Extensions.Logging.*`. Here are a few points that may clarify what I mean, but feel free to correct or respond as needed.

Your configuration uses `AddOpenTelemetry()`, which enables OpenTelemetry logging, and `UseAzureMonitor()`, which configures the `Azure.Monitor.OpenTelemetry.Exporter` to export the log data. When your code logs a message along with an exception, those calls are routed to the OpenTelemetry logger. That logger packages the log data, including the exception, before sending it to the exporter.

You can see this in the OpenTelemetry logger [code](https://github.com/open-telemetry/opentelemetry-dotnet/blob/7a1c35fa17831283d1b97a8b54e8fbae2494257c/src/OpenTelemetry/Logs/ILogger/OpenTelemetryLogger.cs#L68), where the log record is created and the exception is included. You can also review how the Azure Monitor exporter [handles exceptions](https://github.com/Azure/azure-sdk-for-net/blob/daf2487603a9643b3731ad81fa697ec9e1fd5c2c/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/LogsHelper.cs#L72) in its export logic. If the exception data isn’t being exported, the issue is most likely within the exporter itself.

You can easily verify this by switching to a different exporter—such as the OpenTelemetry console exporter and checking whether the exception appears there. Also note that this behavior is not related to the formatter. Formatters are not strictly required to format exceptions by default, even though the logging APIs include an exception parameter. See @davidfowl’s [comment](https://github.com/dotnet/dotnet-api-docs/issues/10318#issuecomment-2308973224) for the reasoning behind this design.

The logger itself can choose how to handle and output the exception. For example, the[`JsonConsoleFormatter`](https://github.com/dotnet/runtime/blob/b54c5d53ca8208e9bb5c95a2fbbd27f30df09b9d/src/libraries/Microsoft.Extensions.Logging.Console/src/JsonConsoleFormatter.cs#L51) writes out the exception string regardless of the formatted message.

For OpenTelemetry, the logger simply constructs the log record and hands it off to the exporter to process and it is up to the exporter how to handle the exception data.

**Comment by bh3605** [comment]
@tarekgh While I dive into the links you've provided, are you able to answer why I'm seeing double telemetry and am also seeing the structured exception logs throw this "Field 'method' on type 'StackFrame' is required but missing or empty"?

**Comment by tarekgh** [comment]
You are logging the exception twice, so it is expected to see it twice. Why are you doing that?

```C#
  logger.LogError(exception, "Log the ex");
  logger.LogError(exception, "Exception caught and converted to ProblemDetails {@ProblemDetails}", details);
```

> seeing the structured exception logs throw this "Field 'method' on type 'StackFrame' is required but missing or empty"

Without more information, it’s hard to determine the exact cause. One possibility is that one of the logged exceptions doesn’t contain a valid stack trace. Here is an example of situation where this type of error can occur:

https://github.com/microsoft/ApplicationInsights-Go/blob/9194eea52d6fe5313a2b109056254baca9ab3194/README.md?plain=1#L539

**Comment by bh3605** [comment]
I'm logging it twice because it's being logged a different way and none of what I care about is working so I'm trying different ways and it's not working. From my screenshots, you can see neither are being logged.

``` csharp
logger.LogTrace("Trace 1");
logger.LogWarning("Warning 1");
logger.LogError("Error 1");
logger.LogCritical("Critical 1");
````

Again, as you can see from the screenshots, all of these telemetry items are being logged and they are being logged twice. Do you know why that may be the case?

**Comment by tarekgh** [comment]
Could you check if there is any other logger registered in your scenario? do you run on Azure and somehow have configuration like enabling app insights logging?

**Comment by bh3605** [comment]
I whipped up a MVP for the missing exception logs. I'm able to narrow it down to a few different stack traces the logger/exporter/whoever likes and doesn't like.

Here's the MVP to reproduce the behavior. It looks like this is a problem with Lamar.
``` csharp
public class Startup
{
	private IConfigurationManager Configuration;

	public Startup(IConfigurationManager configuration)
	{
		Configuration = configuration;
	}

	public void Configure(WebApplicationBuilder builder)
	{
		builder.Logging.ClearProviders();
	}

	public void ConfigureHost(IHostBuilder host)
	{
		host.UseLamar();
	}

	public void ConfigureServices(IServiceCollection services)
	{
		services.AddTransient<BrokenInterface, BrokenConcreteClass>();
		services.AddOpenTelemetry().UseAzureMonitor();
		services.AddProblemDetails();
		services.AddExceptionHandler<ExceptionToProblemDetailsHandler>();
		services.AddTransient(provider =>
		{
			throw new InvalidOperationException("throw an exception.");
			var svc = new MyService();

			return svc;
		});

		services.AddControllers();
		services.AddEndpointsApiExplorer();

		services.AddAuthorization();
		services.AddSwaggerGen();
	}

	public void ConfigureMiddleware(WebApplication app, Action<SwaggerOptions>? swaggerSetupAction = null)
	{
		app.UseExceptionHandler();
		app.UseStatusCodePages();
		app.UseSwagger(swaggerSetupAction);
		app.UseSwaggerUI();

		app.UseAuthentication();
		app.UseAuthorization();
		app.UseHttpsRedirection();

		app.MapControllers().RequireAuthorization();
	}
}

public class MyService { }

public interface BrokenInterface
{

}

public class BrokenConcreteClass : BrokenInterface
{
	public BrokenConcreteClass(MyService service)
	{

	}
}

[ApiController]
public class NotBrokenController : ControllerBase
{
	public NotBrokenController(MyService myService)
	{

	}

	[HttpGet, ApiVersion("1")]
	[Route("api/nobreak")]
	[AllowAnonymous]
	public async Task<HttpResponseMessage> Get()
	{
		return new HttpResponseMessage(HttpStatusCode.OK);
	}
}

[ApiController]
public class BrokenController : ControllerBase
{
	private readonly BrokenInterface myService;

	public BrokenController(BrokenInterface myService)
	{
		this.myService = myService;
	}

	[HttpGet, ApiVersion("1")]
	[Route("api/break")]
	[AllowAnonymous]
	public async Task<HttpResponseMessage> Get()
	{
		return new HttpResponseMessage(HttpStatusCode.OK);
	}
}

// Program.cs
var builder = WebApplication.CreateBuilder(args);

var startup = new Startup(builder.Configuration);
startup.Configure(builder);
startup.ConfigureHost(builder.Host);
startup.ConfigureServices(builder.Services);

var app = builder.Build();
startup.ConfigureMiddleware(app);
app.Run();
```

Here are the different stack traces from the MVP
```
telemetry upload fails
   at IdCard.WebApi.Startup.<>c.<ConfigureServices>b__4_0(IServiceProvider provider) in C:\Users\me\source\repos\myteam\Project\Project.WebApi\Setup.cs:line 42
   at Lamar.IoC.Scope.TryGetInstance(Type serviceType)
   at Lamar.IoC.Scope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeFilterPipelineAsync>g__Awaited|20_0>d.MoveNext()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d.MoveNext()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d.MoveNext()
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.<Invoke>d__11.MoveNext()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.<Invoke>d__5.MoveNext()
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext()
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<<Invoke>g__Awaited|10_0>d.MoveNext()

telemetry upload succeeds
   at IdCard.WebApi.Startup.<>c.<ConfigureServices>b__4_0(IServiceProvider provider) in C:\Users\me\source\repos\myteam\Project\Project.WebApi\Setup.cs:line 42
   at Lamar.IoC.Resolvers.TransientLambdaResolver`2.Build(Scope scope)
   at Lamar.IoC.Resolvers.TransientResolver`1.Resolve(Scope scope)
   at Lamar.IoC.Instances.LambdaInstance`2.<ToResolver>b__14_0(Scope scope)
   at Lamar.IoC.Scope.TryGetInstance(Type serviceType)
   at Lamar.IoC.Scope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeFilterPipelineAsync>g__Awaited|20_0>d.MoveNext()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d.MoveNext()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d.MoveNext()
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.<Invoke>d__11.MoveNext()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.<Invoke>d__5.MoveNext()
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext()
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<<Invoke>g__Awaited|10_0>d.MoveNext()
```

Here are the stacktraces in my project
```
telemetry upload fails
stacktrace
   at MyProject.Infrastructure.CardMedia.ClarityBindingFactory.LoadClientCertificate() in C:\Users\me\source\repos\myteam\MyProject\MyProject.Infrastructure\CardMedia\ClarityClientFactory.cs:line 54
   at MyProject.Infrastructure.ServiceCollectionExtensions.<>c.<AddInfrastructure>b__0_1(IServiceProvider provider) in C:\Users\me\source\repos\myteam\MyProject\MyProject.Infrastructure\ServiceCollectionExtensions.cs:line 44
   at Lamar.IoC.Instances.GeneratedInstance.<>c__DisplayClass9_1.<BuildFuncResolver>b__0(Scope s) in Lamar.IoC.Instances\GeneratedInstance.cs:line 206
   at Lamar.IoC.Scope.TryGetInstance(Type serviceType) in Lamar.IoC\Scope.cs:line 181
   at Lamar.IoC.Scope.GetService(Type serviceType) in Lamar.IoC\Scope.cs:line 134
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext) in /_/src/Mvc/Mvc.Core/src/Controllers/ControllerFactoryProvider.cs:line 60
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) in /_/src/Mvc/Mvc.Core/src/Infrastructure/ControllerActionInvoker.cs:line 70
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync() in /_/src/Mvc/Mvc.Core/src/Infrastructure/ControllerActionInvoker.cs:line 465
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeFilterPipelineAsync>g__Awaited|20_0>d.MoveNext() in /_/src/Mvc/Mvc.Core/src/Infrastructure/ResourceInvoker.cs:line 250
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d.MoveNext() in /_/src/Mvc/Mvc.Core/src/Infrastructure/ResourceInvoker.cs:line 124
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d.MoveNext() in /_/src/Mvc/Mvc.Core/src/Infrastructure/ResourceInvoker.cs:line 129
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.<Invoke>d__11.MoveNext() in /_/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs:line 195
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext() in /_/src/Security/Authentication/Core/src/AuthenticationMiddleware.cs:line 75
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.<Invoke>d__6.MoveNext() in /_/src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs:line 75
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__7.MoveNext() in /_/src/Swashbuckle.AspNetCore.Swagger/SwaggerMiddleware.cs:line 43
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext() in /_/src/Middleware/Diagnostics/src/StatusCodePage/StatusCodePagesMiddleware.cs:line 51
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<<Invoke>g__Awaited|10_0>d.MoveNext() in /_/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddlewareImpl.cs:line 98

serializationstacktracestring
   at MyProject.Infrastructure.CardMedia.ClarityBindingFactory.LoadClientCertificate() in C:\Users\me\source\repos\myteam\MyProject\MyProject.Infrastructure\CardMedia\ClarityClientFactory.cs:line 54
   at MyProject.Infrastructure.ServiceCollectionExtensions.<>c.<AddInfrastructure>b__0_1(IServiceProvider provider) in C:\Users\me\source\repos\myteam\MyProject\MyProject.Infrastructure\ServiceCollectionExtensions.cs:line 44
   at (ArrayClosure, Scope)
   at Lamar.IoC.Instances.GeneratedInstance.<>c__DisplayClass9_1.<BuildFuncResolver>b__0(Scope s)
   at Lamar.IoC.Scope.TryGetInstance(Type serviceType)
   at Lamar.IoC.Scope.GetService(Type serviceType)
   at lambda_method9(Closure, IServiceProvider, Object[])
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)


telemetry upload succeeds
stacktrace
   at MyProject.Infrastructure.CardMedia.ClarityBindingFactory.LoadClientCertificate() in C:\Users\me\source\repos\myteam\MyProject\MyProject.Infrastructure\CardMedia\ClarityClientFactory.cs:line 54
   at MyProject.Infrastructure.ServiceCollectionExtensions.<>c.<AddInfrastructure>b__0_1(IServiceProvider provider) in C:\Users\me\source\repos\myteam\MyProject\MyProject.Infrastructure\ServiceCollectionExtensions.cs:line 44
   at Lamar.IoC.Resolvers.TransientLambdaResolver`2.Build(Scope scope) in Lamar.IoC.Resolvers\TransientLambdaResolver.cs:line 17
   at Lamar.IoC.Resolvers.TransientResolver`1.Resolve(Scope scope) in Lamar.IoC.Resolvers\TransientResolver.cs:line 15
   at Lamar.IoC.Instances.LambdaInstance`2.<ToResolver>b__14_0(Scope scope) in Lamar.IoC.Instances\LambdaInstance.cs:line 89
   at Lamar.IoC.Scope.TryGetInstance(Type serviceType) in Lamar.IoC\Scope.cs:line 181
   at Lamar.IoC.Scope.GetService(Type serviceType) in Lamar.IoC\Scope.cs:line 134
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext) in /_/src/Mvc/Mvc.Core/src/Controllers/ControllerFactoryProvider.cs:line 60
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) in /_/src/Mvc/Mvc.Core/src/Infrastructure/ControllerActionInvoker.cs:line 70
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync() in /_/src/Mvc/Mvc.Core/src/Infrastructure/ControllerActionInvoker.cs:line 465
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeFilterPipelineAsync>g__Awaited|20_0>d.MoveNext() in /_/src/Mvc/Mvc.Core/src/Infrastructure/ResourceInvoker.cs:line 250
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d.MoveNext() in /_/src/Mvc/Mvc.Core/src/Infrastructure/ResourceInvoker.cs:line 124
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d.MoveNext() in /_/src/Mvc/Mvc.Core/src/Infrastructure/ResourceInvoker.cs:line 129
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.<Invoke>d__11.MoveNext() in /_/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs:line 195
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext() in /_/src/Security/Authentication/Core/src/AuthenticationMiddleware.cs:line 75
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.<Invoke>d__6.MoveNext() in /_/src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs:line 75
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__7.MoveNext() in /_/src/Swashbuckle.AspNetCore.Swagger/SwaggerMiddleware.cs:line 43
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext() in /_/src/Middleware/Diagnostics/src/StatusCodePage/StatusCodePagesMiddleware.cs:line 51
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<<Invoke>g__Awaited|10_0>d.MoveNext() in /_/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddlewareImpl.cs:line 98

serializationstacktracestring
   at MyProject.Infrastructure.CardMedia.ClarityBindingFactory.LoadClientCertificate() in C:\Users\me\source\repos\myteam\MyProject\MyProject.Infrastructure\CardMedia\ClarityClientFactory.cs:line 54
   at MyProject.Infrastructure.ServiceCollectionExtensions.<>c.<AddInfrastructure>b__0_1(IServiceProvider provider) in C:\Users\me\source\repos\myteam\MyProject\MyProject.Infrastructure\ServiceCollectionExtensions.cs:line 44
   at Lamar.IoC.Resolvers.TransientLambdaResolver`2.Build(Scope scope)
   at Lamar.IoC.Resolvers.TransientResolver`1.Resolve(Scope scope)
   at Lamar.IoC.Instances.LambdaInstance`2.<ToResolver>b__14_0(Scope scope)
   at Lamar.IoC.Scope.TryGetInstance(Type serviceType)
   at Lamar.IoC.Scope.GetService(Type serviceType)
   at lambda_method9(Closure, IServiceProvider, Object[])
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)

```

What in the "broken" stack traces is missing a method name?


As far as the double logging, I noticed BatchExportProcessor is being instantiated twice. It's inherited by BatchActivityExportProcessor and LogFilteringProcessor. BatchActivityExportProcessor is instantiated on line 72 and LogFilteringProcessor is instantiated on line 87 in ExporterRegistrationHostedService. Could these two processors be the cause?

**Comment by bh3605** [comment]
FOUND IT. Here's the culprit!

<img width="614" height="533" alt="Image" src="https://github.com/user-attachments/assets/925c31ca-f6a3-4dc7-9022-e92a0f853d4e" />
