### ISSUE TITLE
OperationCanceledException not listed

### ISSUE THREAD

**Issue by nxtn** [dotnet/dotnet-api-docs#1528]
A `System.OperationCanceledException` will be thrown in `System.Net.Http.HttpClient.GetAsync` if a connection has timed out.

https://github.com/dotnet/corefx/blob/bcd20ce6fa0c7580ac4976cb50747687d07d96b2/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L536

**Comment by NextTurn** [comment]
Content Source: [xml/System.Net.Http/HttpClient.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/HttpClient.xml)

**Comment by NextTurn** [comment]
Anyone there?

**Comment by NextTurn** [comment]
The following Linux command returns 403 Forbidden.
```console
curl -I http://azuremigrationcenter.com
```

It seems to be a bug. Related issue dotnet/corefx#20296.

Can you confirm this @karelz? Thanks in advance.

**Comment by NextTurn** [comment]
Stack trace of `System.OperationCanceledException`

```
Unhandled Exception: System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
```

**Comment by NextTurn** [comment]
Stack trace of `System.TaskCanceledException`

```
Unhandled Exception: System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
```

**Comment by ericsampson** [comment]
Pingung @guardrex? :)

**Comment by NextTurn** [comment]
@rpetrusha ping?

**Comment by rpetrusha** [comment]
Thanks for pinging me, @NextTurn., since otherwise this issue would have fallen between the cracks.  I'll address the issue during the current sprint.
