### ISSUE TITLE
SqlConnection throws undocumented ArgumentException

### ISSUE THREAD

**Issue by jzabroski** [dotnet/dotnet-api-docs#3468]
https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.-ctor?view=netframework-4.8

If Application Name passed in is > 128 characters, SqlConnection constructor throws an exception.  Interestingly, SqlConnectionStringBuilder class allows passing into it an Application Name > 128 characters.

```c#
var connectionString = $"Data Source=.;Initial Catalog=master;Integrated Security=true;Application Name={string.Join(string.Empty, Enumerable.Repeat("_", 129))}";
var connectionStringBuilder = new SqlConnectionStringBulder(connectionString);
using (var sqlConn = new SqlConnection(connectionStringBuilder.ToString())
{
	
}
```

Error message:
```
The value's length for key 'application name' exceeds it's limit of '128'.
```

Stack trace:
```
at System.Data.SqlClient.SqlConnectionString.ValidateValueLength(String value, Int32 limit, String key)
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions) 
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at System.Data.SqlClient.SqlConnection..ctor(String connectionString, SqlCredential credential)
   at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at UserQuery.RunUserAuthoredQuery() in C:\Users\john.zabroski\AppData\Local\Temp\LINQPad5\_pogoghlc\query_fnlgxf.cs:line 35
   at LINQPad.ExecutionModel.ClrQueryRunner.Run()
   at LINQPad.ExecutionModel.Server.RunQuery(QueryRunner runner)
   at LINQPad.ExecutionModel.Server.StartQuery(QueryRunner runner)
   at LINQPad.ExecutionModel.Server.<>c__DisplayClass153_0.<ExecuteClrQuery>b__0()
   at LINQPad.ExecutionModel.Server.SingleThreadExecuter.Work()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by mairaw** [comment]
Thanks @jzabroski for your feedback. I'm adding this to our backlog but we can also accept community PRs.

@ajcvickers,@cheenamalhotra, @david-engel to confirm the difference in behavior and if that's expected.

**Comment by David-Engel** [comment]
The maximum length of an Application Name in the connection string is documented on the SqlConnection.ConnectionString Property page:
https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectionstring?view=netframework-4.8#remarks

**Comment by jzabroski** [comment]
@David-Engel Correct, but the path through the system here is not the ConnectionString property, but the constructor taking a raw string value.  Note, the SqlConnectionStringBuilder.ToString() method does not throw the exception in my example, and it's the constructor that throws the exception.

Thanks for your patience!

**Comment by jzabroski** [comment]
@David-Engel It looks like you did the work related to this task in dotnet/SqlClient#435, but I don't see it reflected where I would expect: https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.-ctor?view=dotnet-plat-ext-6.0#system-data-sqlclient-sqlconnection-ctor(system-string) 

Is there something I dont understand?  I saw in your comments from 2020 that you were just onboarding and understanding how this works, too. :)

**Comment by David-Engel** [comment]
Sorry, it looks like this fell through the cracks. The update I made was to ensure the doc update got into the docs for Microsoft.Data.SqlClient (M.D.S):
https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnection.-ctor?view=sqlclient-dotnet-standard-4.0#microsoft-data-sqlclient-sqlconnection-ctor(system-string)

System.Data.SqlClient isn't under active development. M.D.S is the latest SqlClient. But I can submit the same doc change for System.Data.SqlClient.
