### ISSUE TITLE
Make Microsoft.Extensions.Configuration.Xml more tolerant against not supported XML features

### ISSUE THREAD

**Issue by amaic** [dotnet/dotnet-api-docs#8257]
I ran into a problem with the current implementation of Microsoft.Extensions.Configuration.Xml.

With Visual Studio 2019 16.2.1 I created a new  Console App (.NET Framework) application,
added NuGet packages Microsoft.Extensions.Configuration.Xml and NLog.Extensions.Logging,
added code `var configuration = new ConfigurationBuilder().AddXmlFile(Assembly.GetExecutingAssembly().Location + ".config").Build();`
into main function, 
started the program and got an exception:

> System.FormatException
>   HResult=0x80131537
>   Message=XML namespaces are not supported. Line 7, position 22.
>   Source=Microsoft.Extensions.Configuration.FileExtensions
>   StackTrace:
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
>    at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
>    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
>    at ConsoleApp1.Program.Main(String[] args) 

I looked into the generated app.config file and found following XML data:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Configuration.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Primitives" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
The reason of FormatException is attribute "xmlns" of element "assemblyBinding".

I wonder, why files with XML namespace declarations are completely rejected.

My expectation would be, that XML features, that are not yet implemented or cannot be implemented due to their nature of not being mappable to key-value-pairs, 
are ignored, perhaps writing a warning into log file and all other elements are loaded into memory. 

So does it make sense to change the behaviour, instead of throwing an exception ignoring such elements and write a warning into log file?

**Comment by Vaccano** [comment]
I too would love an `IgnoreNameSpaces` flag.  Now I have to roll my own provider of the XML file because of one xml namespace in the configuration file. <sigh>

**Comment by udlose** [comment]
> CC @maryamariyan @eerhardt
> 
> I can imagine folks might have preferences both ways. Some folks might feel confused if we silently dropped members of the XML document, not realizing that it was due to the namespace. That feels like much worse behavior than simply disallowing the namespace.
> 
> What's the scenario for actually using Microsoft.Extensions.Configuration.Xml with namespaces? I see above folks are using it to read a ,NETFramework app.config which doesn't seem like a good idea. Those are meant to be backed with strongly typed configuration data types and much fidelity will be lost. The format expected by Microsoft.Extensions.Configuration.Xml is much simpler: https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration-providers#xml-configuration-provider.
> 
> Maybe I'm missing something here. What's leading folks to use XML files that have namespaces and other content that's not meant for M.E.C.XML?

@ericstj I am creating a .NET Standard 2.0 library that needs to support both .NET Framework (ASP.NET) and .NET configuration styles (app.config, web.config, appsettings.json).  

If I'm going to use M.E.C to handle this, wouldn't I need to use something like the following?

```
            var builder = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddXmlFile("App.config", optional: true, reloadOnChange: true)
                .AddXmlFile("ConsoleApp1.exe.config", optional: true, reloadOnChange: true)
                .AddXmlFile("web.config", optional: true, reloadOnChange: true)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);

            var config = builder.Build();
```

The above code causes the exception the OP provides. How would you suggest doing this?

**Comment by ericstj** [comment]
`AddXmlFile` isn't meant for use with .NETFramework config files - it might work in some cases but it's not something we've recommended.  You can see https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration-providers#xml-configuration-provider for the type of XML files that are meant to be used with the XML configuration provider.

**Comment by udlose** [comment]
> How would you suggest doing this?

Ok, I understand.  How would you suggest doing what I need above then?

**Comment by andy1547** [comment]
@udlose 
I can't speak for your specific use case, but I rolled my own configuration source capable of reading ASP.NET web.config files, to assist in incrementally migrating a ASP.NET WebAPI application to ASP.NET Core. 
I didn't want to duplicate the same settings in both an appsettings.json (or appsettings.Production.json) and a web.config, so I setup the ASP.NET Core application to read from the ASP.NET web.config file, allowing these settings to be accessed through the IConfiguration interface. I've not tested it with an exe.config file (what app.config gets transformed to when building), but I suspect the same solution would work.

```
// usage in ASP.NET Core v6
var builder = WebApplication.CreateBuilder(args); // this will configure standard config sources
var pathToConfig = builder.Configuration["PathToConfig"]; // store path in appsettings.json or in another standard config source 
builder.Configuration.AddXmlConfiguration(pathToWebConfig, false, true); // up to you whether you make this file mandatory or optional

// classes
using Microsoft.Extensions.FileProviders;
using System.Configuration;
using ConfigurationManager = System.Configuration.ConfigurationManager;

public static class ConfigurationBuilderExtensions
{
    public static IConfigurationBuilder AddXmlConfiguration(
        this IConfigurationBuilder builder,
        string path)
        => AddXmlConfiguration(builder, provider: null, path: path, optional: false, reloadOnChange: false);

    public static IConfigurationBuilder AddXmlConfiguration(
        this IConfigurationBuilder builder,
        string path,
        bool optional)
        => AddXmlConfiguration(builder, provider: null, path: path, optional: optional, reloadOnChange: false);

    public static IConfigurationBuilder AddXmlConfiguration(
        this IConfigurationBuilder builder,
        string path,
        bool optional,
        bool reloadOnChange)
        => AddXmlConfiguration(builder, provider: null, path: path, optional: optional, reloadOnChange: reloadOnChange);

    public static IConfigurationBuilder AddXmlConfiguration(
        this IConfigurationBuilder builder,
        IFileProvider provider,
        string path,
        bool optional,
        bool reloadOnChange)
    {
        if (builder == null)
            throw new ArgumentNullException(nameof(builder));

        if (string.IsNullOrWhiteSpace(path))
            throw new ArgumentException("Must not be null/empty", nameof(path));

        return builder.AddXmlConfiguration(s =>
        {
            s.FileProvider = provider;
            s.Path = path;
            s.Optional = optional;
            s.ReloadOnChange = reloadOnChange;
            s.ResolveFileProvider();
        });
    }

    public static IConfigurationBuilder AddXmlConfiguration(
        this IConfigurationBuilder builder,
        Action<XmlConfigurationSource> configureSource)
    {
        var source = new XmlConfigurationSource();
        configureSource.Invoke(source);
        // insert last so other configuration sources (appsettings.json) can override it
        builder.Sources.Insert(0, source);
        return builder;
    }
}

public sealed class XmlConfigurationSource : FileConfigurationSource, IConfigurationSource
{
    public override IConfigurationProvider Build(IConfigurationBuilder builder) => new XmlConfigurationProvider(this);
}

public sealed class XmlConfigurationProvider : FileConfigurationProvider
{
    public XmlConfigurationProvider(FileConfigurationSource source) : base(source) { }

    // TODO: instead of overriding FileConfigurationSource and throwing away stream,
    // This ideally should override ConfigurationProvider instead, however this requires reinventing the wheel
    public override void Load(Stream _)
    {
        var path = Source.FileProvider.GetFileInfo(Source.Path).PhysicalPath;

        ExeConfigurationFileMap map = new()
        {
            ExeConfigFilename = path
        };

        var config = ConfigurationManager.OpenMappedExeConfiguration(map, ConfigurationUserLevel.None);

        Dictionary<string, string> data = new();
        foreach (var key in config.AppSettings.Settings.AllKeys)
        {
            data.Add(key, config.AppSettings.Settings[key].Value);
        }
        // optional, also extract connection strings, using Azure format
        // https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-8.0&tabs=basicconfiguration#connection-string-prefixes
        foreach (var connectionString in config.ConnectionStrings.ConnectionStrings.Cast<ConnectionStringSettings>())
        {
            data.Add($"ConnectionStrings:{connectionString.Name}", connectionString.ConnectionString);
            data.Add($"ConnectionStrings:{connectionString.Name}_ProviderName", connectionString.ProviderName);
        }

        // perform atomic swap
        Data = data;
    }
}
```
Hope this helps.

**Comment by thompson-tomo** [comment]
I too am encountering this issue. I have a desktop app which we use to manage configuration files which could be xml or json. The idea was to use a standardised mechanism for reading the config regardless of source file type.

**Comment by aremes** [comment]
**Schemas**

That's what I need xmlns "support" for.

Once a configuration file gets sufficiently complex, it would be nice to offer customers an .xsd file along with it. Their editors can then guide them through the config process using the xs:documentation content. They can validate the files too! yay!

I agree that ignoring the attributes would be a bad idea. Why not just treat them as any other attribute? i dont care if my IConfiguration has a "Root:xmlns" item. I can ignore that with zero effort when binding the config to my options.

**Comment by rsrokosz-bravurasolutions** [comment]
Having this feature would ease migration off .Net Framework, where typically you'd have in either app.config or a web.config lots of such entries: `<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">` which render such config file unusable for new .Net XML file config provider...
